require("dotenv").config();

module.exports = {
    NODE_ENV:process.env.NODE_ENV || "development",
    PORT:process.env.PORT,
    MONGO_DATABASE_DEV:process.env.MONGODB_URL,


    FIREBASE_API_KEY:process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN:process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID:process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET:process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID:process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID:process.env.FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID:process.env.FIREBASE_MEASUREMENT_ID,


    AWS_ACCESS_KEY:process.env.AWS_ACCESS_KEY,
    AWS_SECRET_KEY:process.env.AWS_SECRET_ACCESS_KEY,

    STRIPE_SECRET_KEY:process.env.STRIPE_SECRET_KEY,
    STRIPE_CARD_ENCRYPTION_KEY:process.env.STRIPE_CARD_ENCRYPTION_KEY
}


